export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || "212410192382-i01kjauguea6p0gec012tft795637itn.apps.googleusercontent.com";
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || "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";
export const SERVER_ROOT_URI = "http://localhost:8080";
export const UI_ROOT_URI = "http://localhost:3000";
export const JWT_SECRET = "secret-key";
export const JWT_TIME = "30m";
export const COOKIE_NAME = "auth_token";
export const PREMIUM = "premium";
export const FREEMIUM = "freemium";